project_id = "pcqblxhcjyomvyyxkqcq"

[functions.generate-website]
verify_jwt = false

[functions.edit-website]
verify_jwt = false

[functions.webhook-inbound]
verify_jwt = false

[functions.send-website-email]
verify_jwt = false

[functions.create-website-checkout]
verify_jwt = false

[functions.stripe-website-webhook]
verify_jwt = false

[functions.hello-world]
enabled = true
verify_jwt = true
import_map = "./functions/hello-world/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello-world/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello-world/*.html" ]
