project_id = "pcqblxhcjyomvyyxkqcq"

[functions.generate-website]
verify_jwt = false

[functions.edit-website]
verify_jwt = false

[functions.webhook-inbound]
verify_jwt = false

[functions.send-website-email]
verify_jwt = false

[functions.create-website-checkout]
verify_jwt = false

[functions.stripe-website-webhook]
verify_jwt = false
